name: Release action

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: bundle the solution
        env:
          BUILD_MODULE_VERSION: ${{ github.event.release.tag_name }}
        shell: pwsh
        run: |
          chmod +x ./bundle/clean.ps1
          chmod +x ./bundle/bundle.ps1
          ./bundle/clean.ps1
          ./bundle/bundle.ps1
        working-directory: ${{ github.workspace }}

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload '${{ github.event.release.tag_name }}' '${{ github.workspace }}/build/pave-module-v${{ github.event.release.tag_name }}.zip'
          gh release upload '${{ github.event.release.tag_name }}' '${{ github.workspace }}/build/pave-full-v${{ github.event.release.tag_name }}.zip'
